nginx:
  build: .
  dockerfile: ./docker/Dockerfile_nginx
  links:
      - node
  ports:
      - "8000:80" # "HOST_PORT:CONTAINER_PORT"
node:
  build: .
  dockerfile: ./docker/Dockerfile_node
  ports:
   - "3000:3000"
  volumes:
   - ./server:/src
  links:
   - redis
   - mongo
  environment:
  - DOCKER_ENV=true

redis:
  image: redis

mongo:
  image: mongo
  ports:
   - "27017:27017"
