nginx:
  build: .
  dockerfile: ./docker/Dockerfile_nginx
  links:
      - node
  ports:
      - "8000:80" # "HOST_PORT:CONTAINER_PORT"
node:
  cpuset: 0,1
  build: .
  dockerfile: ./docker/Dockerfile_node
  ports:
   - "3000:3000"
  volumes:
   # - ./server:/webpack-angular-example/server
   - ./server:/src
  links:
   - redis
   - mongo
  environment:
  - DOCKER_ENV=true

redis:
  image: redis
  ports:
   - "6379:6379"

mongo:
  image: mongo
  ports:
   - "27017:27017"
