FROM ubuntu

# Install curl
RUN apt-get -y install curl

# Install Node
RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

# @ to build some npm modules like socket.io
# Install Python
RUN sudo apt-get install -y python2.7
WORKDIR /usr/bin
RUN ln -s ./python2.7 ./python

# Install make and gcc
RUN sudo apt-get install -y build-essential

# Install libkrb5-dev for kerberos that is one of mongodb's sub-modules
RUN sudo apt-get install -y libkrb5-dev
# to build some npm modules like socket.io @

# Copy app sources
COPY ./dist /webpack-angular-example/dist
COPY ./server /webpack-angular-example/server
COPY ./package.json /webpack-angular-example

# Install global plugins
# RUN npm install -g pm2

# Install app dependencies
RUN cd /webpack-angular-example; npm install --production

# CMD ["executable","param1","param2"]
# CMD ["node", "/webpack-angular-example/server/server.js"]
# CMD ["pm2", "start", "/webpack-angular-example/server/server.js", "-i", "0", "--no-daemon"]
WORKDIR /webpack-angular-example
CMD ["npm", "start"]
